### ISSUE TITLE
Parts of the k8s module doesn't compile

### ISSUE THREAD

**Issue by Petrosz007** [kcl-lang/modules#159]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sh
kcl mod init
kcl mod add k8s
```
In the `main.k`:
```
import k8s.api.apps.v1.stateful_set

statefulSet = stateful_set.StatefulSet {}
```

Run `kcl run main.k`

### 2. What did you expect to see? (Required)
The code compiles

### 3. What did you see instead (Required)
```
failed to compile the kcl package

error[E2L23]: CompileError
  --> /Users/pandi/.kcl/kpm/k8s_1.30/api/apps/v1/stateful_set.k:36:12
   |
36 |     spec?: StatefulSetSpec
   |            ^ name 'StatefulSetSpec' is not defined, did you mean '["StatefulSet"]'?
   |
```

### 4. What is your KCL components version? (Required)

```sh
$ kcl version
0.9.0-rc.1-darwin-arm64
```

`kcl.mod.lock`:
```toml
[dependencies]
  [dependencies.k8s]
    name = "k8s"
    full_name = "k8s_1.30"
    version = "1.30"
    reg = "ghcr.io"
    repo = "kcl-lang/k8s"
    oci_tag = "1.30"
```
